@host=http://localhost:3333
@userEmail=admin@email.com
@userPassword=1
{{
const now = new Date();
const year = now.getFullYear();
const month = now.getMonth();
const date = now.getDate();
exports.start = new Date(new Date().setUTCHours(0,0,0,0)).toISOString();
exports.end = new Date(new Date().setUTCHours(23,59,59,999)).toISOString();
exports.lastWeekStart = new Date(new Date(year, month, date - 7).setUTCHours(0,0,0,0)).toISOString();
exports.lastWeekEnd = new Date(new Date(year, month, date).setUTCHours(23,59,59,999)).toISOString();
exports.firstDayOfMonth = new Date(new Date(year, month, 2).setUTCHours(0,0,0,0)).toISOString();
exports.lastDayOfMonth = new Date(new Date(year, month + 1, 1).setUTCHours(23,59,59,999)).toISOString();
exports.now = now.toISOString();
}}

###
# Register
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: application/json
{
    "email": "{{userEmail}}",
    "password": "{{userPassword}}"
}

###
# Login
# @name jwt
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json
{
    "email": "{{userEmail}}",
    "password": "{{userPassword}}"
}

###
# User Info
# @ref jwt
GET {{host}}/api/user/info HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

# Work time Summary

###
# GET Work-time summary for this month
GET {{host}}/api/work-time/summary?from={{firstDayOfMonth}}&to={{lastDayOfMonth}} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Work-time summary for today
GET {{host}}/api/work-time/summary?from={{start}}&to={{end}} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Recalculate work-time summary for this month
GET {{host}}/api/work-time/summary/recalculate?from={{firstDayOfMonth}}&to={{lastDayOfMonth}} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# CREATE new work-time summary
# @name json
POST {{host}}/api/work-time/summary HTTP/1.1
Authorization: Bearer {{jwt.access_token}}
Content-Type: application/json
{
    "date": start,
    "time": 20
}

###
# GET work-time summary
# @ref json
GET {{host}}/api/work-time/summary/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# UPDATE work-time summary
# @ref json
PATCH {{host}}/api/work-time/summary/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}
Content-Type: application/json
{
    "time": 90
}

###
# DELETE work-time
# @ref json
DELETE {{host}}/api/work-time/summary/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}


# Task


###
# GET Array of tasks
GET {{host}}/api/work-time/task HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Array of tasks for today
GET {{host}}/api/work-time/task?from={{start}}&to={{end}} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Array of tasks for the last week
GET {{host}}/api/work-time/task?from={{lastWeekStart}}&to={{lastWeekEnd}} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Array of incomplete tasks for the last week
GET {{host}}/api/work-time/task?from={{lastWeekStart}}&to={{lastWeekEnd}}&incomplete=true HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Array of incomplete tasks for the last week (includeAll)
GET {{host}}/api/work-time/task?from={{lastWeekStart}}&to={{lastWeekEnd}}&incomplete=true&includeAll=true HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# CREATE new task
# @name json
POST {{host}}/api/work-time/task HTTP/1.1
Authorization: Bearer {{jwt.access_token}}
Content-Type: application/json
{
    "date": "2023-01-28T15:38:39Z",
    "name": "Task name",
    "comment": "Comment",
    "completeness": 30,
    "excludedFromSearch": false
}

###
# GET task
# @ref json
GET {{host}}/api/work-time/task/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# UPDATE task
# @ref json
PATCH {{host}}/api/work-time/task/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}
Content-Type: application/json
{
    "completeness": 90,
    "excludedFromSearch": true
}

###
# DELETE task
# @ref json
DELETE {{host}}/api/work-time/task/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}


# Timestamp


###
# GET Timestamps for today
GET {{host}}/api/work-time/timestamp HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Timestamps for some date
@date=2022-01-11
GET {{host}}/api/work-time/timestamp?date={{date}} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# GET Raw Timestamps
@raw=true
GET {{host}}/api/work-time/timestamp?raw={{raw}} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# CREATE new timestamp
# @name json
POST {{host}}/api/work-time/timestamp HTTP/1.1
Authorization: Bearer {{jwt.access_token}}
Content-Type: application/json
{
    "timestamp": "{{now}}",
    "type": "Start"
}

###
# GET timestamp
# @ref json
GET {{host}}/api/work-time/timestamp/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}

###
# UPDATE timestamp
# @ref json
PATCH {{host}}/api/work-time/timestamp/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}
Content-Type: application/json
{
    "type": "StartBreak"
}

###
# DELETE timestamp
# @ref json
DELETE {{host}}/api/work-time/timestamp/{{ json.data._id }} HTTP/1.1
Authorization: Bearer {{jwt.access_token}}