version: '3.1'
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3000:3333'
    env_file:
      - ./envs/.api.env
  graphql:
    container_name: graphql
    build:
      context: ./
      dockerfile: ./apps/graphql/Dockerfile
    ports:
      - '3001:3334'
    env_file:
      - ./envs/.graphql.env
  account:
    container_name: account
    build:
      context: ./
      dockerfile: ./apps/account/Dockerfile
    env_file:
      - ./envs/.account.env
  work-time:
    container_name: work-time
    build:
      context: ./
      dockerfile: ./apps/work-time/Dockerfile
    env_file:
      - ./envs/.work-time.env
  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
  rmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
